const comments = {
  tabs: [
    { id: 1, status: '全部' },
    { id: 2, status: '待处理' },
    { id: 3, status: '已完成' },
  ],
  commentLists: [
    {
      id: 1,
      name: 'John Doe',
      avatar: 'https://via.placeholder.com/150',
      comment: 'This is a great product!',
      likes: '122',
      date: '2022-01-01',
      status: 'pending',
    },
    {
      id: 2,
      name: 'Jane Smith',
      avatar: 'https://via.placeholder.com/150',
      comment: 'I love this product!',
      likes: '12',
      date: '2022-01-02',
      status: 'done',
    },
    {
      id: 3,
      name: 'Bob Johnson',
      avatar: 'https://via.placeholder.com/150',
      comment: 'This is a great product!',
      likes: '221',
      date: '2022-01-03',
      status: 'pending',
    },
    {
      id: 4,
      name: 'Alice Brown',
      avatar: 'https://via.placeholder.com/150',
      comment: 'I love this product!',
      likes: '24',
      date: '2022-01-04',
      status: 'done',
    },
    {
      id: 5,
      name: 'Charlie Davis',
      avatar: 'https://via.placeholder.com/150',
      comment: 'This is a great product!',
      likes: '24',
      date: '2022-01-05',
      status: 'pending',
    },
    {
      id: 6,
      name: 'David Miller',
      avatar: 'https://via.placeholder.com/150',
      comment: 'I love this product!',
      likes: '64',
      date: '2022-01-06',
      status: 'done',
    },
    {
      id: 7,
      name: 'Emily Wilson',
      avatar: 'https://via.placeholder.com/150',
      comment: 'This is a great product!',
      likes: '25',
      date: '2022-01-07',
      status: 'pending',
    },
    {
      id: 8,
      name: 'Frank Lee',
      avatar: 'https://via.placeholder.com/150',
      comment: 'I love this product!',
      likes: '241',
      date: '2022-01-08',
      status: 'done',
    },
    {
      id: 9,
      name: 'Grace Taylor',
      avatar: 'https://via.placeholder.com/150',
      comment: 'This is a great product!',
      likes: '52',
      date: '2022-01-09',
      status: 'pending',
    },
    {
      id: 10,
      name: 'Henry White',
      avatar: 'https://via.placeholder.com/150',
      comment: 'I love this product!',
      likes: '245',
      date: '2022-01-10',
      status: 'done',
    },
  ],
}

export default comments
