import type { Metadata } from 'next'
import React from 'react'
import '@/components/styles/globals.css'
import { ThemeProvider } from '@/components/theme-provider'
import { SynesFont } from '@/components/fonts/fonts'
import { ReactNode } from 'react'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode
}>) {
  return (
    // 差异不会影响功能，添加 suppressHydrationWarning 解决水合问题
    <html lang="zh-CN" suppressHydrationWarning>
      <body className={`${SynesFont.className} antialiased  `}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
